pedroSG94/RootEncoder

- app/src/main/java/com/pedro/rtmpstreamer/customexample/RtmpActivity.java
- app/src/main/java/com/pedro/rtmpstreamer/customexample/RtspActivity.java
- app/src/main/java/com/pedro/rtmpstreamer/defaultexample/ExampleRtmpActivity.java
- app/src/main/java/com/pedro/rtmpstreamer/defaultexample/ExampleRtspActivity.java
- app/src/main/java/com/pedro/rtmpstreamer/displayexample/DisplayRtmpActivity.java
- app/src/main/java/com/pedro/rtmpstreamer/displayexample/DisplayRtspActivity.java
- app/src/main/java/com/pedro/rtmpstreamer/filestreamexample/RtmpFromFileActivity.java
- app/src/main/java/com/pedro/rtmpstreamer/filestreamexample/RtspFromFileActivity.java
- app/src/main/java/com/pedro/rtmpstreamer/surfacemodeexample/SurfaceModeRtmpActivity.java
- app/src/main/java/com/pedro/rtmpstreamer/surfacemodeexample/SurfaceModeRtspActivity.java
- app/src/main/java/com/pedro/rtmpstreamer/texturemodeexample/TextureModeRtmpActivity.java
- app/src/main/java/com/pedro/rtmpstreamer/texturemodeexample/TextureModeRtspActivity.java
- app/src/main/res/layout/activity_texture_mode.xml
- builder/src/main/AndroidManifest.xml
- builder/src/main/java/com/pedro/rtplibrary/DecodersTest.java
- builder/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java
- builder/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera2.java
- builder/src/main/java/com/pedro/rtplibrary/rtmp/RtmpDisplay.java
- builder/src/main/java/com/pedro/rtplibrary/rtmp/RtmpFromFile.java
- builder/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java
- builder/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera2.java
- builder/src/main/java/com/pedro/rtplibrary/rtsp/RtspDisplay.java
- builder/src/main/java/com/pedro/rtplibrary/rtsp/RtspFromFile.java
- builder/src/main/java/com/pedro/rtplibrary/source/Camera1Source.java
- builder/src/main/java/com/pedro/rtplibrary/source/Camera2Source.java
- builder/src/main/java/com/pedro/rtplibrary/source/DisplaySource.java
- builder/src/main/java/com/pedro/rtplibrary/source/FromFileSource.java
- builder/src/main/java/com/pedro/rtplibrary/view/AutoFitTextureView.java
Refactored `builder` package and classes 
* approach is based on `video-source-type` and `purpose` as previous implementations names lacked description. 
* previous implementation names implied that they were based on the `Builder` pattern
* the `base` classes configure and manage: 
* Camera (1 or 2), Mic Managers, Video - Audio Encoders and Muxer 
* package name is `rtplibrary`  this clarifyies what it is and its purpose
> refactor based on purpose & video-source-type

- app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java
- encoder/src/main/java/com/pedro/encoder/input/gl/SpriteGestureController.java
Added option in SpriteGestureController (default on).
In the demo app, you can freely move Image but Text and Gif only in view boundaries
> prevent move object outside

- encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java
Add setZoom(Float level) to precisely control zoom level for camera2.
setZoom(Float level) also set zoomLevel class member so you can switch between direct value control and pinches.
Use getMaxZoom() to retrieve current camera max zoom level.
This API aims to develop a slider that control zoom level.
Also, setZoom(MotionEvent) also call setZoom(float).
> Add API setZoom to control zoom with a level value for camera2.

- rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera2.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpDisplay.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpFromFile.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpOnlyAudio.java
See this [commit](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/b5b818a4c5ab094e81a57064f56c6a0d7f78f64a)
Now uses .poll() instead of .take() on the LinkedBlockingQueue. I haven't noticed any issues with this, but this could require testing on different units (tested and works on SM930, Samsung Galaxy 7, Android 8)
> Add stats for dropped frames, reset functions for counters & FLV bugfix

- encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java
From the Android docs:
> Sets recording mode hint. This tells the camera that the intent of the application is to record videos, not to take still pictures. 
Makes the camera much smoother on some old and cheap devices.
> Recording mode hint

- encoder/build.gradle
- rtmp/build.gradle
- rtplibrary/build.gradle
- rtsp/build.gradle
When Proguard is run on an app, it's not run on the app as a whole with all of its libraries included. Because of this, `proguardFiles` actually has no effect on an Android library (marked with the `com.android.library` plugin).
`consumerProguardFiles` is what libraries use in order to tell apps using the library about their Proguard configs. None of the libraries in this project have any actual Proguard configs, but if that changes, this will prevent users of the library from having to manually include them in their apps.
> Expose Proguard configs to library consumers

- encoder/src/main/AndroidManifest.xml
- encoder/src/main/res/values/strings.xml
- rtmp/src/main/AndroidManifest.xml
- rtmp/src/main/res/values/strings.xml
- rtplibrary/src/main/AndroidManifest.xml
- rtplibrary/src/main/res/values/strings.xml
- rtsp/src/main/AndroidManifest.xml
- rtsp/src/main/res/values/strings.xml
Every Android library needs a manifest, but that manifest doesn't actually have to contain any meaningful info besides the package name. In some cases, it can be harmful to provide extra info. For example, each library here specifies `android:supportsRtl="true"`. This is an attribute meant for apps to specify whether or not they support RTL layouts (Arabic, Hebrew, etc). By default, its value is `false`, because most developers don't support or test RTL layouts for their apps. However, apps [merge](https://developer.android.com/studio/build/manifest-merge) their libraries' manifests into their own when building APKs, so specifying `android:supportsRtl` here means that apps that use these libraries will suddenly start being laid out differently in RTL languages, probably without their …
> Remove unnecessary Android manifest attributes and resources

- encoder/src/main/java/com/pedro/encoder/audio/AudioEncoder.java
- encoder/src/main/java/com/pedro/encoder/audio/DataTaken.java
- encoder/src/main/java/com/pedro/encoder/input/audio/GetMicrophoneData.java
- encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java
- encoder/src/main/java/com/pedro/encoder/input/decoder/AudioDecoder.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/OnlyAudioBase.java
In 561ab6a, a byte[] was replaced with a ByteBuffer. I have been trying to use parts of this library, and was getting a lot of audio "crackling" when streaming to YouTube. (Note: I have not tried to use older versions of the library, nor have I tried to do other things with this library than stream to YouTube.)
There were a couple reasons for the crackling, which I think is related to #277, that I was able to fix; the bigger one (I'll talk about the smaller one later today on the issue) was that when I printed out the data being recorded from the audio the buffers all started with 4 bytes of 0 and seemed "shifted".
I tracked the issue down to ByteBuffer not storing its data at the beginning of its underlying backing array (which also might be larger than the requested size): you have to …
> Track ByteBuffer offset, to avoid audio crackling.

- README.md
"camera2" features are non-existing. Adding them to AndroidManifest caused the app to be incompatible with any device in Play Store.
Resolves #411
> Remove non-existing features for AndroidManifest from README

- app/src/main/AndroidManifest.xml
added required permission `FOREGROUND_SERVICE`
> fix: demo app service rtp crashes immediately

- encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java
Some devices such as the Pixel 4 are not automatically selecting the correct profile level which is causing some streaming services to reject the stream.
Using the demo app I tested dumping the results of an ffprobe when broadcasting to an nginx server.  At 640x480 a Pixel 2 correctly reported a profile level of 3.0 whereas the Pixel 4 reported 1.0 which is invalid according to the h.264 spec.  After adding this change and forcing the profile level to 3.0 ffprobe reported the correct profile.
> Add ability to configure AVC Profile and Profile Level

- encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java
1. AudioPlaybackCaptureConfiguration which was added in Android Q (29) let us capture internal audio without microphone when you're using MediaProjection. So, in DisplayBase instead of prepareAudio() we can call new prepareInternalAudio() method to capture ONLY internal audio.
2. In MicrophoneManager when we call createMicrophone() only MediaRecorder.AudioSource.DEFAULT was used by default. But, e.g., MediaRecorder.AudioSource.CAMCODER records sound with better quality and without extraneous noise. So, let the user choose the audio source.
> Usage of the newest AudioPlaybackCaptureConfiguration (added in Android Q)

- encoder/src/main/java/com/pedro/encoder/input/decoder/AudioDecoder.java
Hi :)
I found a problem with `AudioDecoder.java` when I was trying to stream rtmp from file and the input file has mono sound. 
The output audio from the library was corrupted. The bug is the size of `pcmBuffer` variable which is set up for stereo audio and it's not reinitialized when `channels` variable is set to 1 in `initExtractor` function. Please take a look :)
> fixed problem in Audio encoder when streaming rtmp from file

- .gitignore
- rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java
In some cases audio frames are filling up mFlvTagCache and causing all video frames to be dropped since they're added to a full queue.  Using `put()` causes the operation to wait for an open slot instead of discarding the frame.
> Fix issue where audio frames fill up mFlvTagCache

- encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java
- encoder/src/main/java/com/pedro/encoder/input/video/Camera2Helper.java
- encoder/src/main/java/com/pedro/encoder/input/video/CameraHelper.java
Summary of changes
- Always depend on camera ids from cameramanager. getCameraIdList instead of hardcoded ones
- Not having cameraCharactericstics in a field so it always reflects currently selected camera
What do you think @pedroSG94 ?
> Refactored Camera2ApiManager to not depend on hardcoded camera ids

- rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java
Hi @pedroSG94 
Small PR. I need to log dropped and sent frames to Analytics. Currently, it's hard to grab dropped frames after a stream has been disconnected as they are cleared right before Disconnected callback.
I just moved clearing frames after the callback.
> Resetting frames after disconnect callback

- encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java
Fixed a bug where the surfaceview was not visible when entering background during streaming or recoding
>  screen is not visible when entering the background during streaming

- encoder/src/main/java/com/pedro/encoder/input/audio/AudioPostProcessEffect.java
If you'll look at AutomaticGainControl.create(int audioSession), AcousticEchoCanceler.create(int audioSession) and NoiseSuppressor.create(int audioSession) methods you'll find that them could return null, so we should check for null value before calling setEnabled(true) or NullPointerException would be thrown.
> Fixed NullPointerException(s) in AudioPostProcessEffect class

- encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java
Before `zoomLevel` would not get updated from the non motion event method. This resolves that issue and ensures it's updated for either method (given the zoom does not throw an exception)
> Update zoom level for non motion events

- rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java
Avoiding the thrown exception should improve performance (and it's a bit cleaner)
> Use queue offer instead of add

- encoder/src/main/java/com/pedro/encoder/audio/AudioEncoder.java
- encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java
On some devices I see `IllegalArgument` exception sometimes thrown when the encoder is unhappy with unsupported configuration.
But we should probably catch all exceptions here. So I made this catch all exception types.
> Catch all exception types during encoder creation

- rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java
Hi @pedroSG94 
I'm migrating to the llnw authorization that you added (thanks a lot for that). I had a problem that it didn't work for me.
It turned out that the connection timeout of 5 seconds is not enough and it stops the stream during the connection.
I've noticed that there is a call `connectingLock.wait(5000)` in the `RtmpConnection.rtmpConnect()` method.
But this is called at the beginning of the whole connection process and not for each `connect` command.
When you use authorization everything is sent three times, like the handshake, connect, etc. That's why 5 seconds may not be enough to connect. In my case, it was usually ~7 seconds but it depends on the server. For some other streams I used, it took only 2 seconds. So just for safety, I set 15 seconds timeout for authorized …
> Increased connection timeout for authorized connections

- rtmp/build.gradle
- rtmp/src/main/java/com/pedro/rtmp/utils/AuthUtil.kt
- rtmp/src/test/java/com/pedro/rtmp/utils/AuthUtilTest.kt
Hi @pedroSG94 
Looks like the `AuthUtil.bytesToHex()` didn't work well resulting in llnw streams failing.
I was getting IndexOutOfBoundException in this line ```hexChars[j * 2] = hexArray[v ushr 4]```
I suppose that converting mask to byte wasn't necessary.
> Fixed bytes to hex function

- rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpClient.kt
- rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspClient.kt
Often, RTMPS URLs are provided externally and it should not be necessary to inject a port number into them before this library can use them.
> Default RTMPS port to 443

- rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/OnlyAudioBase.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/recording/BaseRecordController.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/recording/RecordController.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/recording/Status.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/util/AndroidMuxerRecordController.java
Created the BaseRecordController component to allow setting up a custom RecordController to record video in other formats that accept h264 and aac or in mp4 using something different from AndroidMuxer (Xuggler or JCodec for example)
By default the AndroidMuxerRecordController class is used.
> BaseRecordController

- encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java
- rtplibrary/src/main/java/com/pedro/rtplibrary/util/sources/VideoManager.kt
Hi, I would like to use any camera using camera1 api.
This uses `cameraSelect` outside of Camera1Base
I found that VideoManager.kt needs a modification to work with my changes, should I keep the original `start()` to avoid any breakage ?
> allow selection of all cameras with camera1

- encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java
The position of the csd0byteBuffer passed as an argument of extractVpsSpsPpsFromH265 has been unintentionally moved forward by Buffer#get().
Therefore, you should rewind the buffer.
> Fix issue that H265 stream is not in video file

- rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java
Fix memory leak in case start/stop stream multiple times:
Before fix:
After fix:
> Fix memory leak in case start/stop stream multiple times

- encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/AndroidViewFilterRender.java
When an AndroidViewFilter is used, the application uses all the cpu cycles it can, because it renders in a busy loop.
This commit introduces a short sleep when the view does not need to be rendered. 
It would be better to communicate between the main thread and the view rendering thread: to make the view rendering thread wait until it gets notified by the main thread when it is done drawing the frame, and needs another frame. However, this works well enough and requires only a very minor change.
> Make render thread sleep when not rendering to reduce cpu load.

- library/src/main/java/com/pedro/library/util/streamclient/RtmpStreamClient.kt
- library/src/main/java/com/pedro/library/util/streamclient/RtspStreamClient.kt
- library/src/main/java/com/pedro/library/util/streamclient/SrtStreamClient.kt
- library/src/main/java/com/pedro/library/util/streamclient/StreamBaseClient.kt
- rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpClient.kt
- rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpSender.kt
- rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspClient.kt
- rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspSender.kt
- srt/src/main/java/com/pedro/srt/srt/SrtClient.kt
- srt/src/main/java/com/pedro/srt/srt/SrtSender.kt
- Add getItemsInCache method
- Expose setOnlyAudio and setOnlyVideo
> add getItemsInCache and expose setOnlyAudio/setOnlyVideo

- rtmp/src/main/java/com/pedro/rtmp/flv/audio/AacPacket.kt
- rtmp/src/main/java/com/pedro/rtmp/flv/video/H264Packet.kt
- rtmp/src/main/java/com/pedro/rtmp/flv/video/H265Packet.kt
- rtmp/src/main/java/com/pedro/rtmp/utils/Utils.kt
- rtsp/src/main/java/com/pedro/rtsp/rtp/packets/AacPacket.kt
- rtsp/src/main/java/com/pedro/rtsp/rtp/packets/H264Packet.kt
- rtsp/src/main/java/com/pedro/rtsp/rtp/packets/H265Packet.kt
- rtsp/src/main/java/com/pedro/rtsp/utils/Extensions.kt
- srt/src/main/java/com/pedro/srt/mpeg2ts/packets/AacPacket.kt
- srt/src/main/java/com/pedro/srt/mpeg2ts/packets/H26XPacket.kt
- srt/src/main/java/com/pedro/srt/utils/Extensions.kt
- srt/src/test/java/com/pedro/srt/utils/ExtensionTest.kt
refer to:
https://github.com/pedroSG94/RootEncoder/issues/1341
Note:
To avoid duplicated code removeInfo method and test should be moved to common module after merge feature/refactor-commons branch
> fix offset and size of buffers depend of MediaCodec.BufferInfo

- library/src/main/java/com/pedro/library/base/Camera1Base.java
- library/src/main/java/com/pedro/library/base/Camera2Base.java
- library/src/main/java/com/pedro/library/base/DisplayBase.java
- library/src/main/java/com/pedro/library/base/FromFileBase.java
Applying fps to encoder on the fly will not have effect when encoder is already started. Instead fps on the fly should be set to intermediate surface i.e. glInterface
> Fix setLimitFPSOnFly method

- rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManager.kt
- rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManagerAmf0.kt
- rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManagerAmf3.kt
- rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpClient.kt
This pull requests allows a user to set the flashVer / User Agent String that is sent when starting an RTMP stream.
> Allow a custom flashVer string

- library/src/main/java/com/pedro/library/srt/SrtStream.kt
- library/src/main/java/com/pedro/library/util/streamclient/SrtStreamClient.kt
- srt/src/main/java/com/pedro/srt/srt/SrtClient.kt
- srt/src/main/java/com/pedro/srt/srt/SrtSender.kt
This PR adds the ability to set a custom Mpeg2TsService with user-defined parameters for SRT streaming.
- Modified `SrtSender` to accept a custom `Mpeg2TsService` instead of always using the default one
- Added method in `SrtClient` to expose this functionality to higher levels
- Added method in `SrtStream` to make it accessible at the application level
- Added proper handling for streaming state and service reset
```kotlin
// Create custom service
val customService = Mpeg2TsService(
type = 0x01, // Digital TV or custom type
id = 0x1234, // Custom service ID
name = "MyCustomService", // Custom service name
providerName = "MyProvider" // Custom provider name
)
// Set it before streaming starts
srtStream.setMpeg2TsService(customService)
```
- Allows customization of MPEG-TS service …
> Add support for custom Mpeg2TsService in SRT streaming

- encoder/src/main/java/com/pedro/encoder/input/audio/AudioUtils.kt
Fixing mix audio and calculateAmplitude by @itsmeinteger
> fix AudioUtils by @itsmeinteger
