app/src/main/res/layout/activity_texture_mode.xml
=> Fixing preview stretching

app/src/main/java/com/pedro/rtmpstreamer/texturemodeexample/TextureModeRtmpActivity.java, app/src/main/java/com/pedro/rtmpstreamer/texturemodeexample/TextureModeRtspActivity.java, encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java
I have found that in some cases you may not want to preview the back camera but may actually want to make a selection
=> option to select a particular camera for preview

app/build.gradle, encoder/build.gradle, encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java, rtmp/build.gradle, rtmp/src/main/java/com/github/faucamp/simplertmp/DefaultRtmpPublisher.java, rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java, rtmp/src/main/java/net/ossrs/rtmp/CreateSSLSocket.java, rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java, rtmp/src/main/java/net/ossrs/rtmp/TLSSocketFactory.java, rtplibrary/build.gradle, rtsp/build.gradle
In this way we are able to use a secure socket for RTMPS protocol.
=> TLS support for RTMP protocol.

rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/215
=> add description to NetConnection.Connect.Rejected 

encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java
Hello,
Add flash/lantern torch mode for Camera2ApiManager as it was missing. I use the same API as you developed for Camera1ApiManager.
I also add a getter of current Camera CameraCharacteristics so UI elements can be displayed (or not). Example: If flash is not available, do not display flash button.
=> Camera2 flash

rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java, rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera2.java
Added tracking for sent frames & the ability to extend the FlvTagCache. This gives the user the ability to adapt bitrate before you have to drop frames.
=> add stats for video & audio frames sent & FlvTagCache resizing

rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java
Hi, I've found it during digging into your code. I guess it should be bps instead of kb?
=> Fixed comments on setting bitrate methods

app/src/main/java/com/pedro/rtpstreamer/customexample/RtmpActivity.java
It was showing rtsp in rtmp custom example
=> Fix string showed

app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java, encoder/src/main/java/com/pedro/encoder/input/gl/render/ManagerRender.java, encoder/src/main/java/com/pedro/encoder/input/gl/render/ScreenRender.java, encoder/src/main/java/com/pedro/encoder/input/gl/render/SimpleCameraRender.java, encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java, encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java, encoder/src/main/java/com/pedro/encoder/utils/gl/SizeCalculator.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java, rtplibrary/src/main/java/com/pedro/rtplibrary/view/GlInterface.java, rtplibrary/src/main/java/com/pedro/rtplibrary/view/LightOpenGlView.java, rtplibrary/src/main/java/com/pedro/rtplibrary/view/OffScreenGlThread.java, rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java, rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlViewBase.java
Hi @pedroSG94 ,
We need to add flipping only for a stream. The uses case is that the stream should be flipped for the front camera in order for branding, texts to display correctly for the watchers. On the other hand, the preview shouldn't be flipped so user can see how he/she is dancing.
I've also added a callback to notify when camera has been changed so it is easier to react on that.
I've added sample code to OpenGLRtmpActivity to visualize that, but it can be removed.
Let me know what you think.
=> Stream flipping

rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java
I changed the DisplayBase in order to not require the audio permission if the audio is not enable.
Permissions should only be requested when is absolutely necessary, and in case of doing an only-video streaming the audio permission is not necessary at all.
=> Display base: do not require audio permission if the streaming doesn't contain audio

README.md, app/src/main/AndroidManifest.xml, app/src/main/java/com/pedro/rtpstreamer/filestreamexample/RtmpFromFileActivity.java, app/src/main/java/com/pedro/rtpstreamer/filestreamexample/RtspFromFileActivity.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java
- Fixed get audio time from file
- Implemented audio only streaming to Rtsp / Rtmp from file activity
Streaming mp3 files works, but the quality is very bad.
=> Play audio from file

rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/OnlyAudioBase.java, rtplibrary/src/main/java/com/pedro/rtplibrary/util/RecordController.java
- Added startRecord using FileDescriptor in order to support Scoped Storage.
=> Added support for starting record using FileDescriptor

encoder/src/main/java/com/pedro/encoder/audio/AudioEncoder.java, encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java
Sometimes resources are not released. This fixes that
=> On prepareEncoder errors, ensure resources are released

README.md
- Add [Stream](https://getstream.io) sponsorship
=> Add Stream sponsorship

encoder/src/main/java/com/pedro/encoder/input/gl/SurfaceManager.java
Ref: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/789
=> Fix EGL_BAD_MATCH on some devices

app/src/main/java/com/pedro/rtpstreamer/customexample/RtmpActivity.java, encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java
Not very sensitive and need to little long press but we can tweak it later.
=> Tap to focus functionality to Camera1

rtplibrary/src/main/java/com/pedro/rtplibrary/view/AspectRatioMode.java, rtplibrary/src/main/java/com/pedro/rtplibrary/view/LightOpenGlView.java, rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java
To set aspect ratio mode programmatically.
=> Method to set aspect ratio mode

rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java, rtplibrary/src/main/java/com/pedro/rtplibrary/multiple/MultiRtpDisplay.java
- MultiRtpDisplay is based on Camera1 and Camera2 Multistream. It implements DisplayBase.
=> Added MultiRtpDisplay

README.md
=> Update Stream sponsorship

app/src/main/java/com/pedro/rtpstreamer/backgroundexample/RtpService.kt, app/src/main/java/com/pedro/rtpstreamer/displayexample/DisplayService.kt, app/src/main/java/com/pedro/rtpstreamer/utils/ImageAdapter.java, encoder/src/main/java/com/pedro/encoder/audio/AudioEncoder.java, encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/ChromaFilterRender.java, encoder/src/main/java/com/pedro/encoder/utils/CodecUtil.java, encoder/src/main/java/com/pedro/encoder/utils/FaceDetectorUtil.java, encoder/src/main/java/com/pedro/encoder/utils/gl/gif/GifHeaderParser.java, rtmp/src/main/java/com/pedro/rtmp/rtmp/message/RtmpHeader.kt, rtmp/src/main/java/com/pedro/rtmp/rtmp/message/RtmpMessage.kt, rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java, rtplibrary/src/main/java/com/pedro/rtplibrary/view/LightOpenGlView.java, rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java
Used StringBuilder to concat strings;
Unused imports removed;
Const expression used for constant values
=> Used StringBuilder to concat strings;

encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java, rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java
Support for optical (OIS) video stabilization.
=> camera2 support optical video stabilization

encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/object/TextObjectFilterRender.java, encoder/src/main/java/com/pedro/encoder/utils/gl/TextStreamObject.java
Add a possibility to set a background color in TextObjectFilterRender
Preserve backward compatibility
=> Add TextObjectFilter background color

app/src/main/java/com/pedro/streamer/utils/FilterMenu.kt, app/src/main/res/menu/rotation_menu.xml, app/src/main/res/values/strings.xml, encoder/src/main/java/com/pedro/encoder/input/gl/render/ScreenRender.java, encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/CropFilterRender.kt, encoder/src/main/res/raw/screen_fragment.glsl, encoder/src/main/res/raw/simple_fragment.glsl
=> add CropFilterRender

app/src/main/java/com/pedro/streamer/rotation/CameraFragment.kt, app/src/main/res/layout/fragment_camera.xml, common/src/main/java/com/pedro/common/BitrateManager.kt, rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpSender.kt, rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspSender.kt, srt/src/main/java/com/pedro/srt/srt/SrtSender.kt, udp/src/main/java/com/pedro/udp/UdpSender.kt
The bitrate might vary quite drastically (up to 3x the "real" value). By adding a moving average we can avoid this problem. This will also help the adaptive bitrate to work better as it relies on the calculated bitrate.
closes #1517
=> Added exponential moving average to bitrate calculation

encoder/src/main/java/com/pedro/encoder/input/sources/video/Camera2Source.kt, encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.kt
I've added the necessary bits to set the physical camera ID. I'm not an Android developer, so I apologise if my code isn't clean.
=> Support setting physical camera
